spring:
  application:
    name: invoice-tool
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/invoice_tool
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    diver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://${DB_URL}:3306/invoice_tool
    user: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  port: 9000


invoice:
  directory:
    company:
      a: ${COMPANY_A_DIR}
      b: ${COMPANY_B_DIR}

company:
  a: ${COMPANY_A}
  b: ${COMPANY_B}